name: Test pushes with minimal version

on: push

jobs:
  test-latest-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go latest
        uses: actions/setup-go@v2
        with:
          go-version: ~1
      - name: test
        run: make test
  test-minimal-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arnested/go-version-action@v1
        id: go-version
      - name: Install Go ${{ steps.go-version.outputs.minimal }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
      - name: test
        run: make test
